opam-version: "2.0"
lib: [
  "_build/install/default/lib/ocamlformat-rpc/META"
  "_build/install/default/lib/ocamlformat-rpc/dune-package"
  "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.a"
  "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.cma"
  "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.cmi"
  "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.cmt"
  "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.cmx"
  "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.cmxa"
  "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.ml"
  "_build/install/default/lib/ocamlformat-rpc/opam"
]
bin: "_build/install/default/bin/ocamlformat-rpc"
doc: [
  "_build/install/default/doc/ocamlformat-rpc/CHANGES.md"
  "_build/install/default/doc/ocamlformat-rpc/LICENSE.md"
  "_build/install/default/doc/ocamlformat-rpc/README.md"
  "_build/install/default/doc/ocamlformat-rpc/odoc-pages/index.mld"
    {"odoc-pages/index.mld"}
]
man: "_build/install/default/man/man1/ocamlformat-rpc.1"
libexec: "_build/install/default/lib/ocamlformat-rpc/ocamlformat_rpc.cmxs"
